function build_radar_model()
%BUILD_RADAR_MODEL  Programmatically construct radar.slx (codegen-ready).
%
%   Creates a Simulink model with the full radar signal-processing
%   chain as three MATLAB Function blocks in series:
%
%     [rx_cube, look_angle] -> BeamformStage    -> rx_bf
%     [rx_bf, tx]           -> RangeDopplerStage -> RDM_power + axes
%     RDM_power + axes      -> CFARStage        -> detections
%
%   All physical parameters (x_elements, lambda, fs, PRI, mvdr_load,
%   CFAR thresholds) are baked as constants inside each block so the
%   generated C code has zero external dependencies - CLEARANCE just
%   calls radar_step(rx_cube, look_angle, tx) and reads detections.
%
%   Configured for reusable-function code packaging so each radar
%   site in CLEARANCE can allocate its own model instance. - TripleA

    mdl = 'radar';
    if bdIsLoaded(mdl); close_system(mdl, 0); end
    if isfile([mdl '.slx']); delete([mdl '.slx']); end

    new_system(mdl, 'Model');
    open_system(mdl);

    % ---- Model-level configuration -----------------------------------
    preLoadCmd = [ ...
        'run(fullfile(fileparts(which(''radar'')),''model'',''radar_params.m''));' ...
        'run(fullfile(fileparts(which(''radar'')),''model'',''waveform_params.m''));' ...
        'run(fullfile(fileparts(which(''radar'')),''model'',''array_params.m''));'];
    set_param(mdl, 'PreLoadFcn', preLoadCmd);

    set_param(mdl, 'SolverType', 'Fixed-step');
    set_param(mdl, 'Solver',     'FixedStepDiscrete');
    set_param(mdl, 'FixedStep',  'N_pulses * PRI');
    set_param(mdl, 'StopTime',   '16 * N_pulses * PRI');

    % Target file must be set BEFORE reusable-function packaging /
    % RootIOFormat - those parameters only exist under the ERT target.
    set_param(mdl, 'SystemTargetFile', 'ert.tlc');
    set_param(mdl, 'GenCodeOnly',      'on');
    set_param(mdl, 'GenerateMakefile', 'off');

    % Now the code-interface options are visible.
    set_param(mdl, 'CodeInterfacePackaging', 'Reusable function');
    set_param(mdl, 'RootIOFormat',           'Part of model data structure');

    % ---- Root inports ------------------------------------------------
    add_block('built-in/Inport', [mdl '/rx_cube'], ...
        'Port', '1', 'Position', [30 100 60 120]);
    set_param([mdl '/rx_cube'], ...
        'OutDataTypeStr', 'double', ...
        'PortDimensions', '[Nspp_receive 8 16]', ...
        'SampleTime', 'N_pulses * PRI', ...
        'SignalType', 'complex');

    add_block('built-in/Inport', [mdl '/look_angle_rad'], ...
        'Port', '2', 'Position', [30 200 60 220]);
    set_param([mdl '/look_angle_rad'], ...
        'OutDataTypeStr', 'double', ...
        'PortDimensions', '1', ...
        'SampleTime', 'N_pulses * PRI');

    add_block('built-in/Inport', [mdl '/tx'], ...
        'Port', '3', 'Position', [30 300 60 320]);
    set_param([mdl '/tx'], ...
        'OutDataTypeStr', 'double', ...
        'PortDimensions', '[Nspp 1]', ...
        'SampleTime', 'N_pulses * PRI', ...
        'SignalType', 'complex');

    % ---- Processing stages -------------------------------------------
    add_matlab_function_block([mdl '/BeamformStage'],    [200 80 380 200], beamform_stage_code());
    add_matlab_function_block([mdl '/RangeDopplerStage'], [450 80 630 200], range_doppler_stage_code());
    add_matlab_function_block([mdl '/CFARStage'],         [700 80 880 220], cfar_stage_code());

    % ---- Root outports -----------------------------------------------
    add_block('built-in/Outport', [mdl '/det_range_m'],       'Port', '1', 'Position', [950 90 980 110]);
    add_block('built-in/Outport', [mdl '/det_velocity_mps'],  'Port', '2', 'Position', [950 130 980 150]);
    add_block('built-in/Outport', [mdl '/det_snr_dB'],        'Port', '3', 'Position', [950 170 980 190]);
    add_block('built-in/Outport', [mdl '/n_detections'],      'Port', '4', 'Position', [950 210 980 230]);

    % ---- Wiring ------------------------------------------------------
    add_line(mdl, 'rx_cube/1',           'BeamformStage/1',      'autorouting', 'on');
    add_line(mdl, 'look_angle_rad/1',    'BeamformStage/2',      'autorouting', 'on');
    add_line(mdl, 'BeamformStage/1',     'RangeDopplerStage/1',  'autorouting', 'on');
    add_line(mdl, 'tx/1',                'RangeDopplerStage/2',  'autorouting', 'on');
    add_line(mdl, 'RangeDopplerStage/1', 'CFARStage/1',          'autorouting', 'on');
    add_line(mdl, 'RangeDopplerStage/2', 'CFARStage/2',          'autorouting', 'on');
    add_line(mdl, 'RangeDopplerStage/3', 'CFARStage/3',          'autorouting', 'on');
    add_line(mdl, 'CFARStage/1',         'det_range_m/1',        'autorouting', 'on');
    add_line(mdl, 'CFARStage/2',         'det_velocity_mps/1',   'autorouting', 'on');
    add_line(mdl, 'CFARStage/3',         'det_snr_dB/1',         'autorouting', 'on');
    add_line(mdl, 'CFARStage/4',         'n_detections/1',       'autorouting', 'on');

    save_system(mdl);
    fprintf('Built codegen-ready %s.slx\n', mdl);
end

% =========================================================================
% Helpers
% =========================================================================

function add_matlab_function_block(fullPath, position, script)
    add_block('simulink/User-Defined Functions/MATLAB Function', fullPath);
    set_param(fullPath, 'Position', position);
    sfr = sfroot;
    ch  = sfr.find('-isa', 'Stateflow.EMChart', 'Path', fullPath);
    ch.Script = script;
end

% -------------------------------------------------------------------------
% Codegen-safe block code. Physical constants baked in as literals so the
% generated C code has zero external state dependencies. - TripleA
% -------------------------------------------------------------------------

function s = beamform_stage_code()
s = [ ...
'function rx_bf = fcn(rx_cube, look_angle_rad)' newline ...
'%#codegen' newline ...
'    N_el     = 8;' newline ...
'    fc       = 2.8e9;' newline ...
'    c        = 2.99792458e8;' newline ...
'    lambda   = c / fc;' newline ...
'    d        = lambda / 2;' newline ...
'    mvdr_load = 0.001;' newline ...
'    x_elements = ((0:N_el-1) - (N_el-1)/2)'' * d;' newline ...
'    [Nspp, ~, N_pulses] = size(rx_cube);' newline ...
'    rx_stacked = reshape(permute(rx_cube, [1 3 2]), [], N_el);' newline ...
'    [~, w_mvdr] = mvdr_beamform(rx_stacked, x_elements, lambda, look_angle_rad, mvdr_load);' newline ...
'    rx_bf = complex(zeros(Nspp, N_pulses));' newline ...
'    for n = 1:N_pulses' newline ...
'        rx_bf(:, n) = rx_cube(:, :, n) * conj(w_mvdr);' newline ...
'    end' newline ...
'end' newline];
end

function s = range_doppler_stage_code()
s = [ ...
'function [RDM_power, range_axis_m, velocity_axis_mps] = fcn(rx_bf, tx)' newline ...
'%#codegen' newline ...
'    fc     = 2.8e9;' newline ...
'    c      = 2.99792458e8;' newline ...
'    lambda = c / fc;' newline ...
'    fs     = 250e3;' newline ...
'    PRI    = 10e-3;' newline ...
'    [RDM, range_axis_m, velocity_axis_mps] = range_doppler(rx_bf, tx, fs, lambda, PRI);' newline ...
'    RDM_power = abs(RDM).^2;' newline ...
'end' newline];
end

function s = cfar_stage_code()
% Codegen-safe: no find, no logical indexing, no sort of variable-size
% arrays. Single pass over the RDM keeping a top-K list of detections
% and accumulating noise floor from non-detection cells. Final top-K
% sort is a bubble sort over a fixed-size (K=16) buffer - trivially
% codegen-safe. Same behaviour as the piecewise CFARStage code but
% all indexing is scalar arithmetic. - TripleA
s = [ ...
'function [det_range_m, det_velocity_mps, det_snr_dB, n_detections] = fcn(RDM_power, range_axis_m, velocity_axis_mps)' newline ...
'%#codegen' newline ...
'    MAX_DETECTIONS = int32(16);' newline ...
'    N_guard_range = 4;  N_train_range = 8;' newline ...
'    N_guard_dop   = 1;  N_train_dop   = 2;' newline ...
'    Pfa           = 1e-6;' newline ...
'    det_mask = cfar_ca(RDM_power, N_guard_range, N_train_range, N_guard_dop, N_train_dop, Pfa);' newline ...
'    det_range_m      = nan(double(MAX_DETECTIONS), 1);' newline ...
'    det_velocity_mps = nan(double(MAX_DETECTIONS), 1);' newline ...
'    det_snr_dB       = nan(double(MAX_DETECTIONS), 1);' newline ...
'    top_p = zeros(double(MAX_DETECTIONS), 1);' newline ...
'    top_r = zeros(double(MAX_DETECTIONS), 1);' newline ...
'    top_d = zeros(double(MAX_DETECTIONS), 1);' newline ...
'    n_found     = int32(0);' newline ...
'    noise_sum   = 0.0;' newline ...
'    noise_count = 0.0;' newline ...
'    [N_r, N_d] = size(RDM_power);' newline ...
'    for r = 1:N_r' newline ...
'        for d = 1:N_d' newline ...
'            p = RDM_power(r, d);' newline ...
'            if det_mask(r, d)' newline ...
'                if n_found < MAX_DETECTIONS' newline ...
'                    n_found = n_found + int32(1);' newline ...
'                    top_p(double(n_found)) = p;' newline ...
'                    top_r(double(n_found)) = r;' newline ...
'                    top_d(double(n_found)) = d;' newline ...
'                else' newline ...
'                    min_val = top_p(1);  min_idx = int32(1);' newline ...
'                    for k = 2:double(MAX_DETECTIONS)' newline ...
'                        if top_p(k) < min_val' newline ...
'                            min_val = top_p(k);  min_idx = int32(k);' newline ...
'                        end' newline ...
'                    end' newline ...
'                    if p > min_val' newline ...
'                        top_p(double(min_idx)) = p;' newline ...
'                        top_r(double(min_idx)) = r;' newline ...
'                        top_d(double(min_idx)) = d;' newline ...
'                    end' newline ...
'                end' newline ...
'            else' newline ...
'                noise_sum   = noise_sum + p;' newline ...
'                noise_count = noise_count + 1.0;' newline ...
'            end' newline ...
'        end' newline ...
'    end' newline ...
'    if noise_count > 0.0' newline ...
'        noise_floor = noise_sum / noise_count;' newline ...
'    else' newline ...
'        noise_floor = eps;' newline ...
'    end' newline ...
'    % Bubble-sort top-K by power descending (K <= 16 so cost is bounded)' newline ...
'    n_used = double(n_found);' newline ...
'    for i = 1 : n_used - 1' newline ...
'        for j = 1 : n_used - i' newline ...
'            if top_p(j) < top_p(j+1)' newline ...
'                t = top_p(j); top_p(j) = top_p(j+1); top_p(j+1) = t;' newline ...
'                t = top_r(j); top_r(j) = top_r(j+1); top_r(j+1) = t;' newline ...
'                t = top_d(j); top_d(j) = top_d(j+1); top_d(j+1) = t;' newline ...
'            end' newline ...
'        end' newline ...
'    end' newline ...
'    for k = 1 : n_used' newline ...
'        det_range_m(k)      = range_axis_m(top_r(k));' newline ...
'        det_velocity_mps(k) = velocity_axis_mps(top_d(k));' newline ...
'        det_snr_dB(k)       = 10 * log10(max(top_p(k), eps) / max(noise_floor, eps));' newline ...
'    end' newline ...
'    n_detections = n_found;' newline ...
'end' newline];
end
